<?xml version="1.0"?>
<!--

Gazebo Shredder Definition File
Author: James Jackson

-->

<robot name="neo" xmlns:xacro="http://ros.org/wiki/xacro">

<!-- Properties -->
<xacro:property name="namespace" value="$(arg robot_namespace)" />
<xacro:property name="use_mesh_file" value="true" />
<xacro:property name="mesh_file" value="package://fcu_sim/meshes/Millennium_Falcon.dae" />
<xacro:property name="mass" value="3.81" /> <!-- [kg] -->
<xacro:property name="body_width" value="0.505" /> <!-- [m] -->
<xacro:property name="body_height" value="0.1" /> <!-- [m] -->
<xacro:property name="rolling_moment_coefficient" value="0.000001" />
<xacro:property name="body_inertia">
  <inertia ixx="0.0347563" ixy="0.0" ixz="0.0" iyy="0.0458929" iyz="0.0" izz="0.0977" />
</xacro:property>


<!-- *********************** GAZEBO ROBOT DEFINITION ******************* -->
<link name="${namespace}/base_link">
  <inertial>
    <mass value="${mass}" />  <!-- [kg] -->
    <origin xyz="0 0 0" />
    <xacro:insert_block name="body_inertia" />
  </inertial>

  <visual>
    <origin xyz="0 0 0" rpy="0 0 0" />
    <geometry>
      <xacro:if value="${use_mesh_file}">
        <mesh filename="${mesh_file}" scale="0.001 0.001 0.001" />
        <!-- <mesh filename="${mesh_file}" scale="1 1 1" /> -->
      </xacro:if>
      <xacro:unless value="${use_mesh_file}">
        <cylinder length="${body_height}" radius="${body_width}"/>
      </xacro:unless>
    </geometry>
  </visual>

  <collision name="collision_mav">
    <origin xyz="0 0 ${body_height/2.0}" rpy="0 0 0" />
    <geometry>
      <cylinder length="${0.1}" radius="${body_width}"/>
    </geometry>
  </collision>

</link>


  <gazebo reference="${namespace}/base_link">
    <material>Gazebo/$(arg color)</material>
  </gazebo>

  <!-- ************************* ROTOR DYNAMICS ********************** -->

  <!-- Simplified Dynamics -->
  <xacro:include filename="$(find fcu_sim_plugins)/xacro/multirotor_forces_and_moments.xacro"/>
  <xacro:mikey_forces_and_moments namespace="${namespace}" parent_link="${namespace}/base_link" command_topic="command"/>


  <!-- ***************** SENSORS ******************* -->
  <!-- Ground Truth -->
  <xacro:include filename="$(find fcu_sim_plugins)/xacro/odometry_sensor.xacro"/>
  <xacro:ground_truth namespace="${namespace}" parent_link="${namespace}/base_link" />

  <!-- Step Camera -->
  <xacro:include filename="$(find fcu_sim_plugins)/xacro/step_camera.xacro"/>
  <xacro:step_camera
    namespace="${namespace}"
    frame_rate="25"
    rgb_range="1000"
    parent_link="${namespace}/base_link"
    image_topic="rgb"
    width="320"
    height="240"
    image_camera_info_topic="camera_info">
    <origin xyz="0.127 0 -0.0889"/>
    <!--<origin xyz="1 1 1"/>-->
  </xacro:step_camera>

  <!-- Laser Scanner -->
  <xacro:include filename="$(find fcu_sim_plugins)/xacro/velodyne.xacro"/>
  <xacro:velodyne_custom
    namespace="${namespace}"
    parent_link="${namespace}/base_link"
    update_rate="25"
    visualize="false">
    <origin xyz="${body_width+0.1} 0 0" rpy="0 0 0"/>
  </xacro:velodyne_custom>

  <!-- GPS -->
  <xacro:include filename="$(find fcu_sim_plugins)/xacro/GPS.xacro"/>
  <xacro:GPS_BYU
    namespace="${namespace}"
    parent_link="${namespace}/base_link"
    GPS_topic="gps"/>

  <!-- Mount an IMU -->
  <xacro:include filename="$(find fcu_sim_plugins)/xacro/imu.xacro"/>
  <xacro:IMU_ADIS16448
    namespace="${namespace}"
    parent_link="${namespace}/base_link"
    imu_topic="imu"/>

  <!-- Contact Sensor -->
  <gazebo reference="${namespace}/base_link">
    <sensor name="contact_sensor" type="contact">
      <always_on>true</always_on>
      <update_rate>1000</update_rate>
      <contact>
        <!-- When using ROS Indigo and Gazebo 2.2.3, the name specified here
             must be <link name>_collision. -->
        <collision>${namespace}/base_link_collision</collision>
      </contact>
      <plugin name="fixed_jaw_bumper" filename="libgazebo_ros_bumper.so">
        <bumperTopicName>${namespace}/contact</bumperTopicName>
        <frameName>contact</frameName>
      </plugin>
    </sensor>
  </gazebo>


</robot>